Add new product(s): products/project-connect.json
publicgoods/products pull request #100
Opened 2021-02-04 18:28 UTC by lacabra

Add new product(s) from [unicef/publicgoods-candidates](https://github.com/unicef/publicgoods/candidates)

2021-02-05 15:21 UTC, conradsp requested changes

2021-02-05 15:21 UTC, conradsp commented on products/project-connect.json
> +  "repositoryURL": "https://github.com/unicef/magicbox-maps",
It says that this repository has been archived. Is this project still active?

2021-02-05 15:21 UTC, conradsp commented on products/project-connect.json
> +      "licenseURL": "https://github.com/unicef/magicbox-maps"
There is no license file in the repository.

2021-02-05 17:36 UTC, lacabra commented on products/project-connect.json
> +  "repositoryURL": "https://github.com/unicef/magicbox-maps",
Yes, they are in the process of redesigning their platform almost from scratch with an external vendor, which will release publicly in the near future. When that happens we will update the link to the new repo. The archiving of this one is housekeeping for what's to come.

2021-02-09 20:17 UTC, lacabra commented on products/project-connect.json
> +      "licenseURL": "https://github.com/unicef/magicbox-maps"
Good catch. There is mention of the license in the README, but not the actual LICENSE file. I'm looking into this. Marking it as `blocked` until I figure this out.

2021-02-11 21:30 UTC, lacabra commented on products/project-connect.json
> +      "licenseURL": "https://github.com/unicef/magicbox-maps"
A proper LICENSE file was added to that repo, and the link updated in bbc1f37

2021-03-04 21:20 UTC, conradsp approved these changes

2021-03-04 21:20 UTC, merged