Add new product(s): products/met-norway-weather-api.json
publicgoods/products pull request #101
Opened 2021-02-09 20:41 UTC by lacabra

Add new product(s) from [unicef/publicgoods-candidates](https://github.com/unicef/publicgoods/candidates)

2021-02-09 21:08 UTC, conradsp requested changes
@lacabra - This appears to be a more complete duplicate of met-norway-weather.json

Propose we delete the old file as a part of this PR.

2021-02-09 21:21 UTC, lacabra commented
@nathanbaleeta 👆 can you please take care of the above comments? Thanks!

2021-02-11 22:03 UTC, nathanbaleeta commented
@conradsp deleted old file (met-norway-weather.json) in commit 6c7aa80

2021-02-11 22:36 UTC, conradsp approved these changes

2021-02-11 22:36 UTC, merged