Add new product(s): products/apache-fineract.json,products/opencrvs.json,products/primero.json,products/x-road.json
publicgoods/products pull request #70
Opened 2020-11-13 12:19 UTC by lacabra

Add new product(s) from [unicef/publicgoods-candidates](https://github.com/unicef/publicgoods/candidates)

2020-11-13 13:56 UTC, conradsp requested changes
I can't find any issues in the Fineract description, but the linter is failing.

2020-11-13 15:19 UTC, lacabra commented
@conradsp There is a problem with the encoding in these automated PRs that get propagated automatically. It's a low priority for me to fix them, I'll keep them fixing manually for now. I confirm that you can't see them on the GitHub online UI, but they come up with a local editor... Also, this PR is the result of our screening of DPGs, where we are updating their status from nominees to DPGs as they meet the DPG Standard, plus in the case of OpenCRVS, we are renaming the file from the long name to the short name. Now it's ready for your review. Thanks 🙏

2020-11-13 19:38 UTC, conradsp requested changes

2020-11-13 19:38 UTC, conradsp commented on products/opencrvs.json
> +  "name": "OpenCRVS",
Can we add an alias to the original name: Open Civil Registration and Vital Statistics

2020-11-13 22:42 UTC, lacabra commented on products/opencrvs.json
> +  "name": "OpenCRVS",
Yes, will do. To account for this properly on my end, I need to implement something a bit more involved, so it may take a few days, but it's on my ToDo now.

2020-11-17 22:54 UTC, lacabra commented on products/opencrvs.json
> +  "name": "OpenCRVS",
Added in 6055b81

2020-11-18 15:01 UTC, conradsp approved these changes

2020-11-18 15:02 UTC, merged