Update DHIS2
publicgoods/products pull request #75
Opened 2020-11-16 22:44 UTC by lacabra

Updated DHIS2 from their full submission to become a fully screened DPG. Like other projects, they prefer to go with the acronym, which results in deleting old file and creating a new one, but which is mostly a rename, plus additional evidence on their SDG relevance. Propagating unicef/publicgoods-candidates#125 where we made sure no information is lost in this update.

2020-11-17 21:04 UTC, conradsp requested changes

2020-11-17 21:04 UTC, conradsp commented on products/dhis2.json
> +  "stage": "nominee"
Should this be updated to DPG?

2020-11-17 22:16 UTC, lacabra commented on products/dhis2.json
> +  "stage": "nominee"
Not yet, but we can wait and leave this open until we have the green light for this one. The full submission is still under review. Either way works, you can merge this now and I will submit another PR when ready, or we can leave this open and will update this one when ready.

2020-11-18 15:00 UTC, conradsp commented on products/dhis2.json
> +  "stage": "nominee"
I'll go ahead and merge, and you can submit a PR whenever the stage changes to DPG.

2020-11-18 15:00 UTC, conradsp approved these changes

2020-11-18 15:00 UTC, merged